const MIN_PASSWORD_LENGTH = 8;
const MAX_PASSWORD_LENGTH = 30;

const MIN_NICKNAME_LENGTH = 3;
const MAX_NICKNAME_LENGTH = 30;

export {
    MIN_PASSWORD_LENGTH,
    MAX_PASSWORD_LENGTH,
    MIN_NICKNAME_LENGTH,
    MAX_NICKNAME_LENGTH
};
